/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jebsoftware.telas;

import br.com.jebsoftware.classes.ContaCorrente;

/**
 *
 * @author TitanNot
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        criaContas();
    }
    
    public final void criaContas(){
        ContaCorrente cc = new ContaCorrente();
        
        cc.setNumero(1);
        cc.setSaldo(1500,null);
        cc.setLimite(1000);
        cc.setEspecial(true);
        
        ContaCorrente cc1 = new ContaCorrente();
        
        cc1.setNumero(2);
        cc1.setSaldo(2000,null);
        cc1.setLimite(1500);
        cc1.setEspecial(true);
        
        ContaCorrente cc2 = new ContaCorrente();
        
        cc2.setNumero(3);
        cc2.setSaldo(3000,null);
        cc2.setLimite(2000);
        cc2.setEspecial(true);
        
        CriaConta.lista_de_contas.add(cc);
        CriaConta.lista_de_contas.add(cc1);
        CriaConta.lista_de_contas.add(cc2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCriaContaCorrente = new javax.swing.JButton();
        btnExcluiContaCorrente = new javax.swing.JButton();
        btnEfetuaSaque = new javax.swing.JButton();
        btnEfetuaDeposito = new javax.swing.JButton();
        btnVerSaldo = new javax.swing.JButton();
        btnEmiteExtrato = new javax.swing.JButton();
        btnEfetuaTransferencia = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Conta Corrente Orientado a Objetos");
        setFocusableWindowState(false);
        setResizable(false);

        jLabel1.setText("Bem vindo ao sistema de conta corrente");

        btnCriaContaCorrente.setText("Criar Conta-Corrente");
        btnCriaContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriaContaCorrenteActionPerformed(evt);
            }
        });

        btnExcluiContaCorrente.setText("Excluir Conta-Corrente");
        btnExcluiContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiContaCorrenteActionPerformed(evt);
            }
        });

        btnEfetuaSaque.setText("Efetuar Saque");
        btnEfetuaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfetuaSaqueActionPerformed(evt);
            }
        });

        btnEfetuaDeposito.setText("Efetuar Depósito");
        btnEfetuaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfetuaDepositoActionPerformed(evt);
            }
        });

        btnVerSaldo.setText("Ver Saldo");
        btnVerSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSaldoActionPerformed(evt);
            }
        });

        btnEmiteExtrato.setText("Emitir Extrato");
        btnEmiteExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmiteExtratoActionPerformed(evt);
            }
        });

        btnEfetuaTransferencia.setText("Efetuar Transferência");
        btnEfetuaTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfetuaTransferenciaActionPerformed(evt);
            }
        });

        jButton8.setText("Sair");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEfetuaDeposito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluiContaCorrente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriaContaCorrente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEfetuaSaque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmiteExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEfetuaTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnVerSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriaContaCorrente)
                    .addComponent(btnVerSaldo))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmiteExtrato)
                    .addComponent(btnExcluiContaCorrente))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEfetuaTransferencia)
                    .addComponent(btnEfetuaSaque))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEfetuaDeposito)
                    .addComponent(jButton8))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnCriaContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriaContaCorrenteActionPerformed
        CriaConta criaconta = new CriaConta();
        criaconta.setVisible(true);
    }//GEN-LAST:event_btnCriaContaCorrenteActionPerformed

    private void btnExcluiContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiContaCorrenteActionPerformed
        ExcluiConta excluiconta = new ExcluiConta();
        excluiconta.setVisible(true);
    }//GEN-LAST:event_btnExcluiContaCorrenteActionPerformed

    private void btnEfetuaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetuaSaqueActionPerformed
        EfetuaSaque es = new EfetuaSaque();
        es.setVisible(true);
    }//GEN-LAST:event_btnEfetuaSaqueActionPerformed

    private void btnEfetuaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetuaDepositoActionPerformed
        EfetuaDeposito ed = new EfetuaDeposito();
        ed.setVisible(true);
    }//GEN-LAST:event_btnEfetuaDepositoActionPerformed

    private void btnVerSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSaldoActionPerformed
        VerSaldo vs = new VerSaldo();
        vs.setVisible(true);
    }//GEN-LAST:event_btnVerSaldoActionPerformed

    private void btnEmiteExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmiteExtratoActionPerformed
        EmiteExtrato ee = new EmiteExtrato();
        ee.setVisible(true);
    }//GEN-LAST:event_btnEmiteExtratoActionPerformed

    private void btnEfetuaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetuaTransferenciaActionPerformed
        EfetuaTransferencia et = new EfetuaTransferencia();
        et.setVisible(true);
    }//GEN-LAST:event_btnEfetuaTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriaContaCorrente;
    private javax.swing.JButton btnEfetuaDeposito;
    private javax.swing.JButton btnEfetuaSaque;
    private javax.swing.JButton btnEfetuaTransferencia;
    private javax.swing.JButton btnEmiteExtrato;
    private javax.swing.JButton btnExcluiContaCorrente;
    private javax.swing.JButton btnVerSaldo;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
